// Package models defines all domain structs and enum types for StratPlan.
//
// Conventions:
//   - Pointer fields (*string, *time.Time, etc.) are nullable in the DB.
//   - json:"-" fields are never serialised to API responses (secrets, hashes).
//   - db:"..." tags map to PostgreSQL column names for pgx scanning.
//   - UUID primary keys are generated by the application, not the DB,
//     so they are available before the INSERT completes.
package models

import (
	"time"

	"github.com/google/uuid"
)

// ── Enums ─────────────────────────────────────────────────────────────────

type Role string

const (
	RoleSuperAdmin      Role = "super_admin"
	RolePlatformSupport Role = "platform_support"
	RoleOrgAdmin        Role = "org_admin"
	RolePlanner         Role = "planner"
	RoleContributor     Role = "contributor"
	RoleViewer          Role = "viewer"
)

func (r Role) IsPlatformRole() bool {
	return r == RoleSuperAdmin || r == RolePlatformSupport
}

func (r Role) CanEditPlans() bool {
	return r == RoleOrgAdmin || r == RolePlanner
}

func (r Role) CanEditActivity() bool {
	return r == RoleOrgAdmin || r == RolePlanner
}

type PlanStatus string

const (
	PlanDraft     PlanStatus = "draft"
	PlanActive    PlanStatus = "active"
	PlanReview    PlanStatus = "review"
	PlanCompleted PlanStatus = "completed"
	PlanArchived  PlanStatus = "archived"
)

type Phase string

const (
	PhaseP1 Phase = "P1"
	PhaseP2 Phase = "P2"
	PhaseP3 Phase = "P3"
)

type ActivityStatus string

const (
	ActivityNotStarted ActivityStatus = "not_started"
	ActivityInProgress ActivityStatus = "in_progress"
	ActivityReview     ActivityStatus = "review"
	ActivityComplete   ActivityStatus = "complete"
)

type ActivityLinkType string

const (
	LinkTypeAuto        ActivityLinkType = "auto"
	LinkTypeManual      ActivityLinkType = "manual"
	LinkTypeAISuggested ActivityLinkType = "ai_suggested"
)

type InviteStatus string

const (
	InvitePending   InviteStatus = "pending"
	InviteAccepted  InviteStatus = "accepted"
	InviteCancelled InviteStatus = "cancelled"
	InviteExpired   InviteStatus = "expired"
)

type SSOProtocol string

const (
	SSOSaml SSOProtocol = "saml"
	SSOOidc SSOProtocol = "oidc"
)

type MilestoneStatus string

const (
	MilestonePending MilestoneStatus = "pending"
	MilestoneReached MilestoneStatus = "reached"
	MilestoneMissed  MilestoneStatus = "missed"
)

type ReportType string

const (
	ReportFullPlan         ReportType = "full_plan"
	ReportExecutiveSummary ReportType = "executive_summary"
	ReportPerPhase         ReportType = "per_phase"
	ReportProgressStatus   ReportType = "progress_status"
	ReportActivityDetail   ReportType = "activity_detail"
	ReportCustom           ReportType = "custom"
)

type ReportFormat string

const (
	ReportPDF  ReportFormat = "pdf"
	ReportDOCX ReportFormat = "docx"
	ReportXLSX ReportFormat = "xlsx"
)

// ReportStatus tracks the lifecycle of a report generation job. Report
// generation currently runs synchronously inside the request that creates
// it, so in practice a row is only ever persisted once it has reached a
// terminal state (complete or failed) — "processing" exists for API-shape
// compatibility with the frontend's polling flow and for a future move to
// background job generation without a breaking response change.
type ReportStatus string

const (
	ReportProcessing ReportStatus = "processing"
	ReportComplete   ReportStatus = "complete"
	ReportFailed     ReportStatus = "failed"
)

// ── Organisation ──────────────────────────────────────────────────────────

// Organisation's profile fields (Address through TotalMembers) are
// self-service — the org's own org_admin fills these in via
// PATCH /api/v1/org (see orgsvc.UpdateOrgProfile) — as opposed to
// Name/Slug/IsActive, which only a platform super_admin can change (see
// adminsvc.UpdateOrg). All profile fields are optional: an org that hasn't
// filled them in yet just omits that context from AI prompts (see
// aisvc.buildOrgContextSection in context.go) rather than failing anything.
type Organisation struct {
	ID       uuid.UUID `json:"id"                   db:"id"`
	Name     string    `json:"name"                 db:"name"`
	Slug     string    `json:"slug"                 db:"slug"`
	LogoURL  *string   `json:"logo_url,omitempty"   db:"logo_url"`
	Locale   string    `json:"locale"               db:"locale"`
	Industry *string   `json:"industry,omitempty"   db:"industry"`
	IsActive bool      `json:"is_active"            db:"is_active"`

	// ── Org profile (self-service, org_admin editable) ──────────────────
	Address      *string `json:"address,omitempty"       db:"address"`
	Country      *string `json:"country,omitempty"       db:"country"`
	ContactEmail *string `json:"contact_email,omitempty" db:"contact_email"`
	ContactPhone *string `json:"contact_phone,omitempty" db:"contact_phone"`
	OrgStructure *string `json:"org_structure,omitempty" db:"org_structure"`
	TotalMembers *int    `json:"total_members,omitempty" db:"total_members"`

	CreatedAt time.Time  `json:"created_at"           db:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"           db:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty" db:"deleted_at"`
}

// ── User ──────────────────────────────────────────────────────────────────

// User represents a person with access to the platform.
// OrgID is nil for platform-tier users (super_admin, platform_support), who
// are not scoped to a single organisation. PasswordHash and SSOSubject are
// never serialised to JSON.
type User struct {
	ID           uuid.UUID  `json:"id"                       db:"id"`
	OrgID        *uuid.UUID `json:"org_id,omitempty"         db:"org_id"`
	Email        string     `json:"email"                    db:"email"`
	PasswordHash *string    `json:"-"                        db:"password_hash"`
	Name         string     `json:"name"                     db:"name"`
	Role         Role       `json:"role"                     db:"role"`
	Locale       string     `json:"locale"                   db:"locale"`
	IsActive     bool       `json:"is_active"                db:"is_active"`
	SSOSubject   *string    `json:"-"                        db:"sso_subject"`
	LastLoginAt  *time.Time `json:"last_login_at,omitempty"  db:"last_login_at"`
	CreatedAt    time.Time  `json:"created_at"               db:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"               db:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at,omitempty"     db:"deleted_at"`
}

// ── TokenClaims ───────────────────────────────────────────────────────────

// TokenClaims are embedded in JWT access tokens. OrgID is nil for
// platform-tier users (super_admin, platform_support).
type TokenClaims struct {
	UserID uuid.UUID
	OrgID  *uuid.UUID
	Role   Role
	Email  string
}

// ── Refresh token ─────────────────────────────────────────────────────────

type RefreshToken struct {
	ID        uuid.UUID  `db:"id"`
	UserID    uuid.UUID  `db:"user_id"`
	TokenHash string     `db:"token_hash"`
	ExpiresAt time.Time  `db:"expires_at"`
	CreatedAt time.Time  `db:"created_at"`
	RevokedAt *time.Time `db:"revoked_at"`
}

// ── SSO config ────────────────────────────────────────────────────────────

type SSOConfig struct {
	ID                 uuid.UUID   `json:"id"                            db:"id"`
	OrgID              uuid.UUID   `json:"org_id"                        db:"org_id"`
	Protocol           SSOProtocol `json:"protocol"                      db:"protocol"`
	MetadataURL        *string     `json:"metadata_url,omitempty"        db:"metadata_url"`
	EntityID           *string     `json:"entity_id,omitempty"           db:"entity_id"`
	Certificate        *string     `json:"-"                             db:"certificate"`
	ClientID           *string     `json:"client_id,omitempty"           db:"client_id"`
	ClientSecret       *string     `json:"-"                             db:"client_secret"`
	DiscoveryURL       *string     `json:"discovery_url,omitempty"       db:"discovery_url"`
	DefaultRole        Role        `json:"default_role"                  db:"default_role"`
	JITEnabled         bool        `json:"jit_enabled"                   db:"jit_enabled"`
	LocalLoginDisabled bool        `json:"local_login_disabled"          db:"local_login_disabled"`
	CreatedAt          time.Time   `json:"created_at"                    db:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"                    db:"updated_at"`
}

// ── Invitation ────────────────────────────────────────────────────────────

type Invitation struct {
	ID         uuid.UUID    `json:"id"                    db:"id"`
	OrgID      *uuid.UUID   `json:"org_id,omitempty"      db:"org_id"`
	Email      string       `json:"email"                 db:"email"`
	Role       Role         `json:"role"                  db:"role"`
	TokenHash  string       `json:"-"                     db:"token_hash"`
	InvitedBy  uuid.UUID    `json:"invited_by"            db:"invited_by"`
	ExpiresAt  time.Time    `json:"expires_at"            db:"expires_at"`
	AcceptedAt *time.Time   `json:"accepted_at,omitempty" db:"accepted_at"`
	Status     InviteStatus `json:"status"                db:"status"`
	PlanIDs    []uuid.UUID  `json:"plan_ids,omitempty"    db:"plan_ids"`
	CreatedAt  time.Time    `json:"created_at"            db:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"            db:"updated_at"`
}

// ── Plan ──────────────────────────────────────────────────────────────────

type Plan struct {
	ID          uuid.UUID  `json:"id"                     db:"id"`
	OrgID       uuid.UUID  `json:"org_id"                 db:"org_id"`
	Title       string     `json:"title"                  db:"title"`
	Description *string    `json:"description,omitempty"  db:"description"`
	Status      PlanStatus `json:"status"                 db:"status"`
	OwnerID     uuid.UUID  `json:"owner_id"               db:"owner_id"`
	StartDate   *time.Time `json:"start_date,omitempty"   db:"start_date"`
	EndDate     *time.Time `json:"end_date,omitempty"     db:"end_date"`
	CreatedAt   time.Time  `json:"created_at"             db:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"             db:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"   db:"deleted_at"`
}

// ── Activity ──────────────────────────────────────────────────────────────

// Activity is a discrete unit of work within a plan phase.
// Content is a flexible JSON blob; AIDraft holds the AI-generated version
// before the user accepts or edits it.
type Activity struct {
	ID         uuid.UUID      `json:"id"                    db:"id"`
	PlanID     uuid.UUID      `json:"plan_id"               db:"plan_id"`
	OrgID      uuid.UUID      `json:"org_id"                db:"org_id"`
	Phase      Phase          `json:"phase"                 db:"phase"`
	Type       string         `json:"type"                  db:"type"`
	Title      string         `json:"title"                 db:"title"`
	UserOrder  int            `json:"user_order"            db:"user_order"`
	Status     ActivityStatus `json:"status"                db:"status"`
	Content    map[string]any `json:"content"               db:"content"`
	AIDraft    map[string]any `json:"ai_draft,omitempty"    db:"ai_draft"`
	AssignedTo []uuid.UUID    `json:"assigned_to,omitempty" db:"assigned_to"`
	DueDate    *time.Time     `json:"due_date,omitempty"    db:"due_date"`
	CreatedAt  time.Time      `json:"created_at"            db:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"            db:"updated_at"`
	DeletedAt  *time.Time     `json:"deleted_at,omitempty"  db:"deleted_at"`
}

// ── Activity link ─────────────────────────────────────────────────────────

// ActivityLink is a directional relationship between two activities.
// Links must be within the same plan.
type ActivityLink struct {
	ID        uuid.UUID        `json:"id"         db:"id"`
	PlanID    uuid.UUID        `json:"plan_id"    db:"plan_id"`
	SourceID  uuid.UUID        `json:"source_id"  db:"source_id"`
	TargetID  uuid.UUID        `json:"target_id"  db:"target_id"`
	LinkType  ActivityLinkType `json:"link_type"  db:"link_type"`
	CreatedBy uuid.UUID        `json:"created_by" db:"created_by"`
	CreatedAt time.Time        `json:"created_at" db:"created_at"`
	UpdatedAt time.Time        `json:"updated_at" db:"updated_at"`
}

// ── Milestone ─────────────────────────────────────────────────────────────

type Milestone struct {
	ID               uuid.UUID       `json:"id"                           db:"id"`
	PlanID           uuid.UUID       `json:"plan_id"                      db:"plan_id"`
	Title            string          `json:"title"                        db:"title"`
	DueDate          time.Time       `json:"due_date"                     db:"due_date"`
	Status           MilestoneStatus `json:"status"                       db:"status"`
	LinkedActivityID *uuid.UUID      `json:"linked_activity_id,omitempty" db:"linked_activity_id"`
	CreatedAt        time.Time       `json:"created_at"                   db:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"                   db:"updated_at"`
}

// ── Report ────────────────────────────────────────────────────────────────

// Report is a generated document (PDF/DOCX/XLSX) covering some slice of a
// plan's data. Sections is only populated for Type == ReportCustom — it
// records which sections the caller chose so the same config can be shown
// back in history. FilePath is where the rendered file lives on disk and is
// never serialised (json:"-"); FileURL is computed at request time by the
// service layer, never persisted, hence db:"-".
type Report struct {
	ID          uuid.UUID      `json:"id"                     db:"id"`
	PlanID      uuid.UUID      `json:"plan_id"                db:"plan_id"`
	OrgID       uuid.UUID      `json:"-"                      db:"org_id"`
	Type        ReportType     `json:"type"                   db:"type"`
	Format      ReportFormat   `json:"format"                 db:"format"`
	Status      ReportStatus   `json:"-"                      db:"status"`
	Sections    map[string]any `json:"sections,omitempty"     db:"sections"`
	FilePath    string         `json:"-"                      db:"file_path"`
	FileURL     *string        `json:"file_url,omitempty"     db:"-"`
	Error       *string        `json:"-"                      db:"error"`
	GeneratedBy uuid.UUID      `json:"generated_by"           db:"generated_by"`
	GeneratedAt time.Time      `json:"generated_at"           db:"generated_at"`
}

// ── Notification log ──────────────────────────────────────────────────────

type NotificationLog struct {
	ID        uuid.UUID      `json:"id"                  db:"id"`
	OrgID     uuid.UUID      `json:"org_id"              db:"org_id"`
	UserID    uuid.UUID      `json:"user_id"             db:"user_id"`
	Type      string         `json:"type"                db:"type"`
	Channel   string         `json:"channel"             db:"channel"`
	Payload   map[string]any `json:"payload"             db:"payload"`
	SentAt    *time.Time     `json:"sent_at,omitempty"   db:"sent_at"`
	Status    string         `json:"status"              db:"status"`
	CreatedAt time.Time      `json:"created_at"          db:"created_at"`
}

// ── Audit log ─────────────────────────────────────────────────────────────

// AuditLog is append-only; rows are never updated or deleted.
type AuditLog struct {
	ID        uuid.UUID      `json:"id"         db:"id"`
	OrgID     uuid.UUID      `json:"org_id"     db:"org_id"`
	UserID    uuid.UUID      `json:"user_id"    db:"user_id"`
	Action    string         `json:"action"     db:"action"`
	TableName string         `json:"table_name" db:"table_name"`
	RecordID  uuid.UUID      `json:"record_id"  db:"record_id"`
	Diff      map[string]any `json:"diff"       db:"diff"`
	CreatedAt time.Time      `json:"created_at" db:"created_at"`
}
